version: '3.3'

networks:               
  db-network: 
    driver: bridge

services:

  mariadb:
    container_name: mariadb
    image: mariadb:10.6-focal
    networks:
      - db-network
    ports:
      - 3306:3306
    restart: always
    volumes:
      - ./db_data:/var/lib/mysql
      - ./db_conf:/etc/mysql
    environment: # lấy từ file .env
      MYSQL_ROOT_PASSWORD: $MYSQL_PASS_ROOT
      MYSQL_DATABASE: $MYSQL_DB
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASS


  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    environment:
      PMA_HOST: mariadb
    ports:
      - "8080:80"
    networks:
      - db-network